spring.application.name=electronics-commerce-platform

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/electronics_commerce
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# SQL initialization
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Redis cache
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
