spring.application.name=electronics-commerce-platform

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/electronics_commerce
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics